// src/components/Sidebar.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { motion } from "framer-motion";
import { 
  LayoutDashboard, 
  Video, 
  Music, 
  Image as ImageIcon, 
  FileText, 
  Repeat, 
  Settings, 
  ShieldCheck,
  Zap,
  ChevronRight,
  Bot
} from "lucide-react";
import { cn } from "@/lib/utils";

const links = [
  { name: "Dashboard", href: "/", icon: LayoutDashboard },
  { name: "Anita Assistant", href: "/assistant", icon: Bot },
  { name: "Video Engine", href: "/video", icon: Video },
  { name: "Audio Studio", href: "/audio", icon: Music },
  { name: "Image Matrix", href: "/image", icon: ImageIcon },
  { name: "PDF Forge", href: "/pdf", icon: FileText },
  { name: "Converter", href: "/converter", icon: Repeat },
];

const secondaryLinks = [
  { name: "Governance", href: "/governance", icon: ShieldCheck },
  { name: "Settings", href: "/settings", icon: Settings },
];

export default function Sidebar() {
  const pathname = usePathname();

  return (
    <motion.aside 
      initial={{ x: -300 }}
      animate={{ x: 0 }}
      className="w-72 h-[calc(100vh-81px)] border-r border-white/5 bg-slate-950/40 backdrop-blur-3xl p-8 sticky top-[81px] overflow-y-auto hidden lg:flex flex-col justify-between"
    >
      <div className="space-y-10">
        <div className="space-y-4">
          <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-[0.3em] px-4">Core Modules</h3>
          <div className="space-y-2">
            {links.map((link) => (
              <SidebarLink 
                key={link.name} 
                link={link} 
                isActive={pathname === link.href || (link.href !== "/" && pathname.startsWith(link.href))} 
              />
            ))}
          </div>
        </div>

        <div className="space-y-4">
          <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-[0.3em] px-4">System</h3>
          <div className="space-y-2">
            {secondaryLinks.map((link) => (
              <SidebarLink 
                key={link.name} 
                link={link} 
                isActive={pathname === link.href} 
              />
            ))}
          </div>
        </div>
      </div>

      <div className="pt-10 border-t border-white/5">
        <div className="p-6 rounded-3xl bg-gradient-to-br from-indigo-500/10 to-purple-500/10 border border-indigo-500/20 relative overflow-hidden group">
          <div className="absolute -top-12 -right-12 w-24 h-24 bg-indigo-500/10 blur-2xl rounded-full group-hover:scale-150 transition-transform duration-700" />
          <div className="relative z-10">
            <div className="flex items-center gap-3 mb-3">
              <Zap className="w-4 h-4 text-indigo-400" />
              <span className="text-[10px] font-black text-white tracking-widest uppercase">Pro Engine</span>
            </div>
            <p className="text-[10px] text-slate-400 font-bold leading-relaxed mb-4">
              Unlock WebGPU acceleration and batch processing.
            </p>
            <button className="w-full py-2.5 rounded-xl bg-indigo-500 text-white text-[10px] font-black tracking-widest uppercase hover:bg-indigo-400 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950">
              Upgrade Now
            </button>
          </div>
        </div>
      </div>
    </motion.aside>
  );
}

function SidebarLink({ link, isActive }: { link: any, isActive: boolean }) {
  return (
    <Link 
      href={link.href}
      className={cn(
        "group flex items-center justify-between px-4 py-3.5 rounded-2xl transition-all duration-300 relative overflow-hidden focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500",
        isActive 
          ? "bg-white/10 text-white shadow-xl shadow-black/20" 
          : "text-slate-400 hover:text-white hover:bg-white/5"
      )}
    >
      {isActive && (
        <motion.div 
          layoutId="active-pill"
          className="absolute left-0 w-1 h-6 bg-indigo-500 rounded-r-full"
        />
      )}
      <div className="flex items-center gap-4 relative z-10">
        <link.icon className={cn(
          "w-5 h-5 transition-transform duration-300 group-hover:scale-110 group-hover:rotate-3",
          isActive ? "text-indigo-400" : "text-slate-500 group-hover:text-white"
        )} />
        <span className="text-xs font-black tracking-widest uppercase">{link.name}</span>
      </div>
      <ChevronRight className={cn(
        "w-4 h-4 transition-all duration-300 opacity-0 group-hover:opacity-100 group-hover:translate-x-1",
        isActive ? "text-indigo-400/50" : "text-slate-600"
      )} />
    </Link>
  );
}

// src/app/layout/sidebar/sidebar.component.ts
import { ChangeDetectionStrategy, Component, output, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import { Store } from '@ngrx/store';
import { selectSidebarCollapsed, selectActiveRoute } from '../../store/app.selectors';
import { toggleSidebar } from '../../store/app.actions';

export interface NavItem {
  label: string;
  icon: string;
  route: string;
  badge: string | null;
}

export const NAV_ITEMS: NavItem[] = [
  { label: 'Dashboard',    icon: 'grid_view',   route: '/',          badge: null },
  { label: 'Video Engine', icon: 'movie',       route: '/video',     badge: '30+' },
  { label: 'Audio Studio', icon: 'music_note',  route: '/audio',     badge: '20+' },
  { label: 'Image Matrix', icon: 'image',       route: '/image',     badge: '10+' },
  { label: 'Converter',    icon: 'sync',        route: '/converter', badge: 'NEW' },
  { label: 'Settings',     icon: 'settings',    route: '/settings',  badge: null },
];

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterModule, MatIconModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <aside class="h-screen glass-panel border-r border-white/10 flex flex-col transition-all duration-400 ease-[cubic-bezier(0.16,1,0.3,1)]"
           [class.w-[260px]]="(collapsed$ | async) === false"
           [class.w-[72px]]="collapsed$ | async">
      
      <!-- Header -->
      <div class="h-16 flex items-center justify-between px-4 border-b border-white/10">
        <div class="flex items-center gap-3 overflow-hidden whitespace-nowrap" [class.opacity-0]="collapsed$ | async" [class.w-0]="collapsed$ | async">
          <div class="w-8 h-8 rounded-lg bg-gradient-to-br from-accent-cyan to-accent-purple flex items-center justify-center shadow-glow">
            <mat-icon class="text-white text-xl">all_inclusive</mat-icon>
          </div>
          <span class="font-bold text-lg tracking-tight">Omni-Tool</span>
        </div>
        @if (collapsed$ | async; as isCollapsed) {
          <button class="w-10 h-10 rounded-lg flex items-center justify-center hover:bg-white/10 transition-colors text-text-secondary hover:text-white shrink-0 focus-visible:ring-2 focus-visible:ring-accent-cyan focus-visible:outline-none"
                  [attr.aria-label]="isCollapsed ? 'Expand sidebar' : 'Collapse sidebar'"
                  [attr.aria-expanded]="!isCollapsed"
                  (click)="onToggleCollapse()">
            <mat-icon>{{ isCollapsed ? 'menu' : 'menu_open' }}</mat-icon>
          </button>
        } @else {
          <button class="w-10 h-10 rounded-lg flex items-center justify-center hover:bg-white/10 transition-colors text-text-secondary hover:text-white shrink-0 focus-visible:ring-2 focus-visible:ring-accent-cyan focus-visible:outline-none"
                  [attr.aria-label]="'Collapse sidebar'"
                  [attr.aria-expanded]="true"
                  (click)="onToggleCollapse()">
            <mat-icon>menu_open</mat-icon>
          </button>
        }
      </div>

      <!-- Navigation -->
      <nav class="flex-1 py-6 px-3 space-y-2 overflow-y-auto overflow-x-hidden">
        @for (item of navItems; track item.route) {
          <a [routerLink]="item.route"
             routerLinkActive="bg-white/10 text-white shadow-[inset_4px_0_0_0_#00f5ff]"
             [routerLinkActiveOptions]="{exact: item.route === '/'}"
             class="flex items-center gap-4 px-3 py-3 rounded-xl text-text-secondary hover:text-white hover:bg-white/5 transition-all duration-300 group relative"
             [title]="(collapsed$ | async) ? item.label : ''">
            
            <mat-icon class="shrink-0 transition-transform duration-300 group-hover:scale-110"
                      [class.text-accent-cyan]="(activeRoute$ | async) === item.route">
              {{ item.icon }}
            </mat-icon>
            
            <span class="font-medium whitespace-nowrap transition-opacity duration-300"
                  [class.opacity-0]="collapsed$ | async"
                  [class.w-0]="collapsed$ | async">
              {{ item.label }}
            </span>

            @if (item.badge && (collapsed$ | async) === false) {
              <span class="ml-auto text-[10px] font-bold px-2 py-0.5 rounded-full bg-accent-purple/20 text-accent-cyan border border-accent-purple/30">
                {{ item.badge }}
              </span>
            }
          </a>
        }
      </nav>

      <!-- Footer Status -->
      <div class="p-4 border-t border-white/10">
        <div class="flex items-center gap-3 px-2">
          <div class="relative flex h-3 w-3 shrink-0">
            <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-status-success opacity-75"></span>
            <span class="relative inline-flex rounded-full h-3 w-3 bg-status-success"></span>
          </div>
          <span class="text-sm font-medium text-text-secondary whitespace-nowrap transition-opacity duration-300"
                [class.opacity-0]="collapsed$ | async"
                [class.w-0]="collapsed$ | async">
            System Online
          </span>
        </div>
      </div>
    </aside>
  `
})
export class SidebarComponent {
  private store = inject(Store);
  navItems = NAV_ITEMS;
  collapsed$ = this.store.select(selectSidebarCollapsed);
  activeRoute$ = this.store.select(selectActiveRoute);
  
  toggleCollapse = output<void>();

  onToggleCollapse() {
    this.store.dispatch(toggleSidebar());
    this.toggleCollapse.emit();
  }
}
