// src/components/Navbar.tsx
"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { Zap, Menu, Bell, Search, User } from "lucide-react";

export default function Navbar() {
  return (
    <motion.nav 
      initial={{ y: -100 }}
      animate={{ y: 0 }}
      className="sticky top-0 z-[100] w-full backdrop-blur-2xl bg-slate-950/60 border-b border-white/5"
    >
      <div className="flex items-center justify-between px-8 py-5 max-w-[1800px] mx-auto">
        <div className="flex items-center gap-12">
          <Link href="/" className="flex items-center gap-4 group">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center font-black text-white shadow-lg shadow-indigo-500/20 group-hover:scale-110 group-hover:rotate-6 transition-all duration-300">
              <Zap className="w-6 h-6 fill-white" />
            </div>
            <div className="flex flex-col">
              <span className="text-xl font-black tracking-tighter text-white leading-none">OMNI-TOOL</span>
              <span className="text-[10px] font-black text-indigo-400 tracking-[0.3em] leading-none mt-1">ENTERPRISE</span>
            </div>
          </Link>

          <div className="hidden lg:flex items-center gap-8">
            <NavLink href="/video" label="Video" />
            <NavLink href="/audio" label="Audio" />
            <NavLink href="/image" label="Image" />
            <NavLink href="/pdf" label="PDF" />
          </div>
        </div>
        
        <div className="flex items-center gap-8">
          <button
            aria-label="Search Commands"
            className="hidden md:flex items-center gap-3 px-4 py-2 rounded-full bg-white/5 border border-white/5 text-slate-400 hover:text-white hover:bg-white/10 transition-all cursor-pointer group focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            <Search className="w-4 h-4 group-hover:scale-110 transition-transform" />
            <span className="text-xs font-bold tracking-wider">SEARCH COMMANDS</span>
            <span className="text-[10px] bg-white/10 px-1.5 py-0.5 rounded border border-white/10 font-mono">⌘K</span>
          </button>

          <div className="flex items-center gap-4">
            <IconButton icon={<Bell className="w-5 h-5" />} ariaLabel="Notifications" />
            <IconButton icon={<User className="w-5 h-5" />} ariaLabel="User Profile" />
            <div className="h-8 w-[1px] bg-white/10 mx-2" />
            <div className="flex items-center gap-3 px-4 py-2 rounded-xl bg-emerald-500/10 border border-emerald-500/20 group cursor-pointer" title="System Status: Online" aria-label="System Status: Online">
              <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse shadow-[0_0_10px_rgba(16,185,129,0.5)]" />
              <span className="text-[10px] font-black text-emerald-500 tracking-widest uppercase">System Online</span>
            </div>
          </div>
        </div>
      </div>
    </motion.nav>
  );
}

function NavLink({ href, label }: { href: string, label: string }) {
  return (
    <Link href={href} className="text-xs font-black text-slate-400 hover:text-white tracking-widest uppercase transition-colors relative group focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none focus-visible:rounded">
      {label}
      <span className="absolute -bottom-2 left-0 w-0 h-[2px] bg-indigo-500 group-hover:w-full transition-all duration-300" />
    </Link>
  );
}

function IconButton({ icon, ariaLabel }: { icon: React.ReactNode, ariaLabel: string }) {
  return (
    <motion.button
      whileHover={{ scale: 1.1, y: -2 }}
      whileTap={{ scale: 0.9 }}
      aria-label={ariaLabel}
      title={ariaLabel}
      className="p-2.5 rounded-xl bg-white/5 border border-white/5 text-slate-400 hover:text-white hover:bg-white/10 transition-all focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
    >
      {icon}
    </motion.button>
  );
}

// src/app/layout/navbar/navbar.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';
import { Store } from '@ngrx/store';
import { selectSystem } from '../../store/app.selectors';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, MatIconModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <header class="h-16 glass-panel border-b border-white/10 flex items-center justify-between px-6 sticky top-0 z-50 transition-all duration-300">
      
      <!-- Search Bar -->
      <div class="flex items-center gap-4 flex-1 max-w-md">
        <div class="relative w-full group">
          <mat-icon class="absolute left-3 top-1/2 -translate-y-1/2 text-text-muted group-focus-within:text-accent-cyan transition-colors">search</mat-icon>
          <input type="text" placeholder="Search tools, tasks, files..." 
                 class="w-full bg-bg-elevated/50 border border-white/10 rounded-xl py-2 pl-10 pr-4 text-sm text-text-primary placeholder-text-muted focus:outline-none focus:border-accent-cyan/50 focus:ring-1 focus:ring-accent-cyan/50 transition-all duration-300">
        </div>
      </div>

      <!-- Actions -->
      <div class="flex items-center gap-4">
        <!-- Status Badge -->
        <div class="hidden md:flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/5 border border-white/10">
          <span class="w-2 h-2 rounded-full" 
                [class.bg-status-success]="(system$ | async)?.networkStatus === 'online'"
                [class.bg-status-error]="(system$ | async)?.networkStatus === 'offline'"></span>
          <span class="text-xs font-medium text-text-secondary">
            {{ (system$ | async)?.networkStatus === 'online' ? 'Connected' : 'Offline' }}
          </span>
        </div>

        <!-- Notifications -->
        <button aria-label="Notifications" class="relative w-10 h-10 rounded-xl flex items-center justify-center hover:bg-white/10 transition-colors text-text-secondary hover:text-white focus-visible:ring-2 focus-visible:ring-accent-cyan focus-visible:outline-none">
          <mat-icon>notifications</mat-icon>
          <span class="absolute top-2 right-2 w-2 h-2 rounded-full bg-accent-pink animate-pulse"></span>
        </button>

        <!-- Profile -->
        <div class="flex items-center gap-3 pl-4 border-l border-white/10">
          <div class="w-8 h-8 rounded-full bg-gradient-to-tr from-accent-purple to-accent-cyan flex items-center justify-center text-sm font-bold shadow-glow">
            K
          </div>
          <div class="hidden md:flex flex-col">
            <span class="text-sm font-medium leading-none">Kapten</span>
            <span class="text-[10px] text-text-muted uppercase tracking-wider mt-1">Admin</span>
          </div>
        </div>
      </div>
    </header>
  `
})
export class NavbarComponent {
  private store = inject(Store);
  system$ = this.store.select(selectSystem);
}
